codecov: true
coveralls: true
language: julia
julia:
  - 1.5.2
  - nightly
  ## - 1.3.1, DArray macro fails; https://github.com/JuliaParallel/DistributedArrays.jl/issues/223

script:
  - julia -e 'using Pkg; Pkg.build(; verbose=true); Pkg.test(coverage=true)';

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
